"""
utils/models.py
===============
Shared Pydantic data models used across all PatentGuard AI modules.
Single source of truth for every data structure in the prototype.
"""

from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


# ── Core record types ─────────────────────────────────────────────────────

class PatentRecord(BaseModel):
    """A single patent or prior-art record returned by a search module."""

    title: str = "Untitled"
    abstract: str = ""
    url: str = ""
    source: str = ""          # "USPTO" | "EPO" | "WIPO" | "Google Patents" | "arXiv" | "GitHub" | "Blog"
    filing_year: Optional[int] = None
    authors: list[str] = Field(default_factory=list)
    record_type: str = "patent"   # "patent" | "prior_art"

    @property
    def text_for_embedding(self) -> str:
        """Concatenated text fed to the embedding model."""
        return f"{self.title}. {self.abstract}".strip()

    def to_row(self) -> dict[str, Any]:
        """Flat dict for Streamlit DataFrame rendering."""
        return {
            "Title": self.title[:80],
            "Source": self.source,
            "Year": self.filing_year or "—",
            "URL": self.url,
        }


# ── Similarity & novelty ──────────────────────────────────────────────────

class ScoredRecord(BaseModel):
    """A PatentRecord annotated with its cosine similarity to the invention."""

    record: PatentRecord
    similarity: float = 0.0     # cosine similarity in [0, 1]
    rank: int = 0

    @property
    def similarity_pct(self) -> str:
        return f"{self.similarity * 100:.1f}%"

    def to_row(self) -> dict[str, Any]:
        row = self.record.to_row()
        row["Similarity"] = self.similarity_pct
        row["Rank"] = self.rank
        return row


class NoveltyReport(BaseModel):
    """Output of the similarity engine for one invention analysis."""

    novelty_score: float            # 0–100 (100 = fully novel)
    risk_level: str                 # LOW | MEDIUM | HIGH
    max_similarity: float           # highest cosine score in corpus
    top_matches: list[ScoredRecord] = Field(default_factory=list)
    invention_embedding: list[float] = Field(default_factory=list)
    corpus_embeddings: list[list[float]] = Field(default_factory=list)

    @property
    def risk_color(self) -> str:
        return {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(self.risk_level, "⚪")

    @property
    def score_label(self) -> str:
        if self.novelty_score >= 70:
            return "✅ Likely Novel"
        elif self.novelty_score >= 40:
            return "⚠️ Partially Novel"
        return "❌ Likely Anticipated"


# ── Patent draft ──────────────────────────────────────────────────────────

class PatentDraft(BaseModel):
    """Structured patent application draft generated by the LLM."""

    title: str = ""
    background: str = ""
    summary: str = ""
    description: str = ""
    claims: list[str] = Field(default_factory=list)
    abstract: str = ""

    def to_plain_text(self) -> str:
        """Render the full draft as a formatted plain-text document."""
        claims_block = "\n".join(
            f"  {i + 1}. {c}" for i, c in enumerate(self.claims)
        )
        return (
            f"TITLE OF THE INVENTION\n{'─' * 40}\n{self.title}\n\n"
            f"ABSTRACT\n{'─' * 40}\n{self.abstract}\n\n"
            f"BACKGROUND OF THE INVENTION\n{'─' * 40}\n{self.background}\n\n"
            f"SUMMARY OF THE INVENTION\n{'─' * 40}\n{self.summary}\n\n"
            f"DETAILED DESCRIPTION\n{'─' * 40}\n{self.description}\n\n"
            f"CLAIMS\n{'─' * 40}\n{claims_block}\n"
        )


# ── Improvements ──────────────────────────────────────────────────────────

class Improvement(BaseModel):
    """A single actionable novelty-improvement suggestion."""

    category: str       # Technical | Claim Scope | Use Case | Combination | Jurisdictional
    suggestion: str
    rationale: str
    priority: int = 3   # 1 = highest impact
